# O Railway vai preencher essas variáveis automaticamente no deploy
spring.datasource.url=${postgresql://postgres:YoRGuvGnuzHeqhOIBzKkwfVHhehrxEkG@postgres.railway.internal:5432/railway}
spring.datasource.username=${postgres}
spring.datasource.password=${YoRGuvGnuzHeqhOIBzKkwfVHhehrxEkG}

# Isso garante que as tabelas da escala sejam geradas/atualizadas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Dialeto do banco (PostgreSQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 