# Dados de conexao com o banco de dados Railway
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=YoRGuvGnuzHeqhOIBzKkwfVHhehrxEkG

# Isso garante que as tabelas da escala sejam geradas/atualizadas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Dialeto do banco (PostgreSQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect