spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:31865/railway
spring.datasource.username=postgres
spring.datasource.password=YoRGuvGnuzHeqhOIBzKkwfVHhehrxEkG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true